on: push
name: Build and test
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    if: '!github.event.deleted'
    strategy:
      matrix:
        php-version: ["7.3", "7.4", "8.0"]
        composer-update: ["", "--prefer-stable --prefer-lowest"]
    steps:
    - uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
        # These extensions are required by PHP 7.4
        extension-csv: mbstring, xmlwriter
        coverage: xdebug
    - name: Composer update
      run: composer update ${{ matrix.composer-update }}
    - name: Unit tests
      run: ./vendor/bin/phpunit
    - name: Unit Codecov
      uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
